### ISSUE TITLE
Bug: Individual plots log scale

### ISSUE THREAD

**Issue by js3110** [pharmaverse/aNCA#118]
### Description
Log scale of individual plots not working

### To reproduce
Outputs -> Ind plots -> log scale

### Expected behaviour

- [x] Should correctly transform to log
- [x] Values =0 filtered out (only for log scale)
- [x] Plot follows same steps as the mean plot counterpart

**Comment by billdenney** [comment]
Related to #125

In general, there should not be negative values in concentration data. Values of 0 should be included in figures to indicate where concentrations go BLQ.

**Comment by billdenney** [comment]
@js3110, I'd recommend keeping 0s in even for log plots as they show in `ggplot2` plots at least. Omitting them makes it harder to understand when concentrations go BLQ. (When I've been in clinical team meetings showing figures where BLQ is excluded, the question almost invariably comes up "Where did those points go?")

A while ago, I made a `scale_y_log10_loq()` that put the limit of quantification on the y axis ticks for `ggplot()` and placed the point off of the axis. I can probably pull that out.

``` r
library(ggplot2)
d_plot <-
  data.frame(
    x = 10:0,
    y = 0:10
  )
plot(y~x, log = "y", data = d_plot)
#> Warning in xy.coords(x, y, xlabel, ylabel, log): 1 y value <= 0 omitted from
#> logarithmic plot
```

![](https://i.imgur.com/GDwGITI.png)

``` r

ggplot(d_plot, aes(x = x, y = y)) +
  geom_point() +
  scale_y_log10()
#> Warning in scale_y_log10(): log-10 transformation introduced infinite values.
```

![](https://i.imgur.com/oAoIckB.png)

<sup>Created on 2024-11-18 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by billdenney** [comment]
It's a default in ggplot, so I don't know why it would not work the same. Can you please point me to the path that data takes to get to making that plot? I would guess that zeros are filtered out along the way. (FYI, negative values won't show up.)

**Comment by js3110** [comment]
@billdenney  yes there are no negative values, only 0s. The updated plot can be found in the bug/individual-plots-log branch in the aNCA/R/general_lineplot.R file. Currently it is set to filter out the values < 0  (lines 106-109) however I just commented those lines out to test and nothing changed in the plot. let me know what you find.
