### ISSUE TITLE
Enhancement: Collaboration with PKNCA

### ISSUE THREAD

**Issue by billdenney** [pharmaverse/aNCA#125]
I just learned of this package, and I'm glad that you're taking it on. I am the primary author of the PKNCA package which I see you're using under the hood. If there are things that would make life easier to have in PKNCA, please let me know (ideally by creating/linking to an issue over there). One specific item that has been on the PKNCA roadmap for a while is to import SDTM (PC and EC/EX) or ADaM (ADPC/ADEX or ADNCA) with less effort (similar to #65).

I'm going to comment on some of the issues where PKNCA already has some support for the desired features and link them here.

**Comment by billdenney** [comment]
FYI, I'm not yet familiar with the working of this project, overall. I will comment on other issues where I think that existing (or desired) PKNCA features can help so that we can more effectively collaborate. Please let me know if I miss the mark about how features are being implemented.

**Comment by js3110** [comment]
Hi @billdenney thank you so much for joining the team! We welcome any advice you can give to us to help implement the PKNCA functions better, and also would love to collaborate with you. I have sent you a message via the Pharmaverse Slack to see if we can set up a meeting- it would be good to give you a run down of the app and its features so we can collaborate more effectively.

**Comment by Gero1999** [comment]
Sounds like a good plan @js3110. I will answer all open suggestions in the issues by @billdenney and we can perhaps also address them deeper during our meeting!
