### ISSUE TITLE
Feature: create new dummy data

### ISSUE THREAD

**Issue by js3110** [pharmaverse/aNCA#13]
Add simulated data for testing.

**Types of Datasets Goal:**

- [ ] Single Dose, Single Analyte IV and EV
- [ ] Single Dose, Multiple Analyte IV and EV
- [ ] Multiple Dose, Single Analyte IV and EV
- [ ] Multiple Dose, Multiple Analyte IV and EV

**Comment by Gero1999** [comment]
Changes made in simulated SD_SA_ORAL.csv 

```
data = read.csv('inst/shiny/data/SD_SA_ORAL1.csv')
data$DOSEA = 70
data$TRT01A = 'Treatment arm A'
data$TRT01P = 'Treatment arm A'
```
