### ISSUE TITLE
Bug: Help Widget not working

### ISSUE THREAD

**Issue by js3110** [pharmaverse/aNCA#22]
**Description**

Help widget in NCA-> Settings -> Slope selection currently not working
(Currently commented out)

**To do:**

- [ ] Fix help widget so that when clicked, instructions for how to carry out inclusions/exclusions pop up
- [ ] Ensure instructions are clear for user

**Comment by js3110** [comment]
Hi @m-kolomanski the code is currently in ui.R around lines 300-400. @Gero1999 made a very useful box which included written instruction and also gifs showing the user how to click on the plots. Since we converted from an app into a package it stopped working.
If you can get them working again, that would be great. And once I have solved issue #23  the plots will look better and we can just rerecord the gifs to match the new plots.

**Comment by m-kolomanski** [comment]
@js3110 

I can work something out.

Currently I cannot see anything to trigger the modal - what was the idea behind it? Should it be displayed when user navigates to the _Slope Selector_ tab? Or should we have _info_ button that pops up the modal?

**Comment by js3110** [comment]
@m-kolomanski 

There was an info button in the ui that we commented out.
I can't seem to find it though so I guess it got deleted instead of commented.
But it just needs to be a little help button (?) that the user can click

**Comment by m-kolomanski** [comment]
Closing with #98
