### ISSUE TITLE
Enhancement: Column definition feature

### ISSUE THREAD

**Issue by Gero1999** [pharmaverse/aNCA#65]
### Description
The user should be able to define from their dataset what columns correspond to what, so the app could do the assignation for them. In other words, instead of the hardcoding of the columns as it is done now, users should be able to pick with different inptus which column corresponds to: 

When implementing take into consideration that these variables are used by PKNCA::PKNCAconc, PKNCA::PKNCAdose and PKNCAdata. 

#### Basic Variables 
- AVAL: Actual Value of Analyte Concentration
- ANALYTE: Analyte measured
- ADOSE: Actual Value of Dose Concentration
- DRUG: Treatment or Drug administrated

#### Time variables
- ARRLT: Actual Relative Time from Reference/Previous Dose
- AFRLT: Actual Relative Time from First Dose

#### Unit measures
- DOSEU: Unit Value of ADOSE
- AVALU: Unit Value of AVAL
- RRLTU: Unit for all time variables (e.g, "hours")

#### Grouping Concentration Variables (used in formulas of PKNCA functions)
- STUDYID: Identification for the Study
- DOSNO: Dose/Cycle number
- ROUTE: Route of administration ("Intravascular" or "Extravascular")
- PCSPEC: Specimen/matrix sample (blood, urine, plasma...) 
- OTHER_GROUPING_COLUMNS: A multiple option should be given to the user so they can keep adding

#### Optional Variables
- ADOSEDUR: Actual Dose Duration 
- NRRLT: Nominal Relative Time from Reference/Previous Dose 

### Definition of Done
The requirements for the feature to be complete:
- [ ] The user can easily specify in "Data" section how its columns are defined
- [ ] The NCA runs well  
- [ ] Hardcoding parts of the code have been substituted for dynamic coding

#### Suggestion
This is a very demanding issue so help should be considered at least to eliminate all hardcoding

**Comment by billdenney** [comment]
Related to #3 and #125

The use of either the `ANALYTE` or `PCTEST` column can replace the need for #3.

I'd like to have a general column identification method for standard data formats (SDTM and ADaM) in PKNCA. That way, it can help others who are doing scripted analysis of NCA, too. While building this out, can it be considered as a general module that may eventually move into the main PKNCA package?

**Comment by Gero1999** [comment]
We could think about it, but not sure how adaptable will be! Our current idea is to allow the user introduce this by selection inputs, although we do want a default automatic filling of those inputs for simplification when ADNCA format is used as the file input
