### ISSUE TITLE
Enhancement: Aesthetics and description of ADPP/PP download 

### ISSUE THREAD

**Issue by Gero1999** [pharmaverse/aNCA#66]
### Description
Currently the ADPP/PP download option is difficult to identify in the App. In order to get it first the NCA should be run:

`NCA > Choose the analyte > Submit > Settings > Choose the Dose Number > Run NCA`

Until here is ok, but then finding the ADPP/PP results is not intuitive for the user:

`Results NCA > CDISC > Export CDISC  (which retrieves a file with the PP/ADPP files)`

Instead an easier alternative should be implemented. As an example:
- Renaming the tab from "CDISC" to "PP/ADPP"
- Showing an in-app-display of the datasets in the tab
- Renaming the download button from "Export CDISC" to "Download PP/ADPP"

### Definition of Done
The requirements for the feature to be complete:
- [ ] After running NCA is easy to identify where to find PP/ADPP files
- [ ] Downloading the files is still possible

**Comment by billdenney** [comment]
Related to #125

I'd love to have PP/ADPP export as part of PKNCA. (That may not be related to this issue specifically.) Would you be interested/willing to shift the code that converts a PKNCAresults object to PP/ADPP into the main PKNCA package?

**Comment by Gero1999** [comment]
Sure, we can think of sharing. Although we still need some refinements, specially on ADPP!
